# listOfNews
{
  listOfNews{
    _id
    title
    short_text
		text
    image_refrence
    images
    tags
    newscategory{
      _id
      title
      category_navbar{
      _id
        title
      }
    }
    source
    time_range
    comment{
      _id
      title
      comment
    }
    likes{
      _id
    }
    dislikes{
      _id
    }
    bookmarks{
      _id
    }
    view{
      _id
    }
  }
}
# listOfNewsById
{
  listOfNewsById(newsId:"64ba296ddaf569c3fba16623"){
    _id
    title
    short_text
		text
    image_refrence
    images
    tags
    newscategory{
      _id
      title
      category_navbar{
      _id
        title
      }
    }
    source
    time_range
    comment{
      _id
      title
      comment
    }
    likes{
      _id
    }
    dislikes{
      _id
    }
    bookmarks{
      _id
    }
    view{
      _id
    }
  }
}
# listOfNewsByCategory
{
  listOfNewsByCategory(categoryId:"649e986ebffcacf051019af1"){
    _id
    title
    short_text
		text
    image_refrence
    images
    tags
    newscategory{
      _id
      title
      category_navbar{
      _id
        title
      }
    }
    source
    time_range
    comment{
      _id
      title
      comment
    }
    likes{
      _id
    }
    dislikes{
      _id
    }
    bookmarks{
      _id
    }
    view{
      _id
    }
  }
}
# listOfCategoryNews
{
  listOfCategoryNews{
    _id
    title
    category_navbar{
      _id
        title
    }
  }
}