# ListOfProduct
{
  listOfProduct{
    _id
    title
    en_title
    introduction
    expert_Check
    images
		imagesUrl
		image_refrence
		image_refrenceUrl
    tags
    category{
      _id
      title
      category_sidebar{
        _id
        title
      }
    }
    subcategory{
      _id
      title
      image
      imageUrl
    }
    main_price
		price
		discount
		count
		description
		seller
    producer{
      _id
     	title
			description
    }
    active
		comments{
      _id
    }
		questions{
      _id
    }
		likes{
      _id
    }
		dislikes{
      _id
    }
		bookmarks{
      _id
    }
  }
}

# ListOfProductById
{
  listOfProductById(id:"64aec38d74fac5c88a73e2e9"){
    _id
    title
    en_title
    introduction
    expert_Check
    images
		imagesUrl
		image_refrence
		image_refrenceUrl
    tags
    category{
      _id
      title
      category_sidebar{
        _id
        title
      }
    }
    subcategory{
      _id
      title
      image
      imageUrl
    }
    main_price
		price
		discount
		count
		description
		seller
    producer{
      _id
     	title
			description
    }
    active
		comments{
      _id
    }
		questions{
      _id
    }
		likes{
      _id
    }
		dislikes{
      _id
    }
		bookmarks{
      _id
    }
  }
}

# ListOfProductByCategoryId
{
  listOfProductByCategory(categoryId:"64876b846a4123bf1176ab29"){
    _id
    title
    en_title
    introduction
    expert_Check
    images
		imagesUrl
		image_refrence
		image_refrenceUrl
    tags
    category{
      _id
      title
      category_sidebar{
        _id
        title
      }
    }
    subcategory{
      _id
      title
      image
      imageUrl
    }
    main_price
		price
		discount
		count
		description
		seller
    producer{
      _id
     	title
			description
    }
    active
		comments{
      _id
    }
		questions{
      _id
    }
		likes{
      _id
    }
		dislikes{
      _id
    }
		bookmarks{
      _id
    }
  }
}
